name: Check SIMDe headers and update clib.json

on:
  schedule:
    - cron: "15 2 * * *" # Runs nightly
  workflow_dispatch: # Allows manual triggering

jobs:
  update-clib-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the clib repository
        uses: actions/checkout@v4

      - name: Clone the SIMDe repository
        run: |
          git clone --depth 1 https://github.com/simd-everywhere/simde-no-tests.git simde-repo

      - name: Generate list of .h files
        id: generate_files
        run: |
          FILE_LIST=$(find simde-repo -type f -name "*.h" | sed 's|simde-repo/||' | sort | tr '\n' ',' | sed 's/,$//')
          echo "::set-output name=file_list::$FILE_LIST"

      - name: Update clib.json
        run: |
          FILES=$(echo "${{ steps.generate_files.outputs.file_list }}" | sed 's/,/","/g')
          jq ".src = [\"$FILES\"]" clib.json > clib.json.tmp
          mv clib.json.tmp clib.json

      - name: Check for changes
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          if [ "$(git diff --name-only HEAD)" ]; then
            git add clib.json
            timestamp=$(date -u)
            git commit -m "Update clib.json with latest SIMDe headers [${timestamp}]" || exit 0
            git push
          else
            echo "No changes to commit."
          fi
